twig:
    form_themes: ['bootstrap_4_layout.html.twig']
    #default_path: '%kernel.project_dir%/templates'

knp_paginator:
    template:
        pagination: "others/twitter_bootstrap_v4_pagination.html.twig"
